-- ---------------------------------------------------------------------------------------------------------
CREATE TABLE COLABORADOR(
    ID				SERIAL PRIMARY KEY NOT NULL,
    NOME			VARCHAR(100) CONSTRAINT colaborador_nome NOT NULL,
    SENHA           VARCHAR(200) CONSTRAINT colaborador_senha NOT NULL,
    TIPO			VARCHAR(50) CONSTRAINT colaborador_tipo CHECK(TIPO IN('Gestor','Vendedor')),
    ATIVO			CHAR(1) CONSTRAINT colaborador_ativo DEFAULT 'S',
    DATACADASTRO	DATE DEFAULT CURRENT_TIMESTAMP,
    IDALTERACAO     INT,
    DATAALTERACAO   DATE
);

CREATE TABLE LOJA(
    ID				SERIAL PRIMARY KEY NOT NULL,
    IDCOLABORADOR	INT REFERENCES COLABORADOR(ID) CONSTRAINT loja_idcolaborador NOT NULL,
    DESCRICAO		VARCHAR(100) CONSTRAINT loja_descricao NOT NULL,
    CODIGOFILIAL	BIGINT CONSTRAINT loja_codigofilial NOT NULL,
    CEP				VARCHAR(50) CONSTRAINT loja_cep NOT NULL,
    CIDADE			VARCHAR(150) CONSTRAINT loja_cidade NOT NULL,
    ESTADO			VARCHAR(150) CONSTRAINT loja_estado NOT NULL,
    ATIVO			CHAR(1) CONSTRAINT loja_ativo DEFAULT 'S',
    DATACADASTRO	DATE DEFAULT CURRENT_TIMESTAMP,
    IDALTERACAO		INT,
    DATAALTERACAO	DATE
);

CREATE TABLE PRODUTO(
    ID				SERIAL PRIMARY KEY NOT NULL,
	IDCOLABORADOR	INT REFERENCES COLABORADOR(ID) CONSTRAINT produto_idcolaborador NOT NULL,
    DESCRICAO		VARCHAR(100) CONSTRAINT produto_descricao NOT NULL,
    CODIGOPRODUTO	BIGINT CONSTRAINT produto_codigoproduto NOT NULL,
	VALORVENDA		MONEY CONSTRAINT produto_valorvenda NOT NULL,
    QUANTIDADE		BIGINT CONSTRAINT produto_quantidade NOT NULL,
    ATIVO			CHAR(1) CONSTRAINT produto_ativo DEFAULT 'S',
    DATACADASTRO	DATE DEFAULT CURRENT_TIMESTAMP,
    IDALTERACAO		INT,
    DATAALTERACAO	DATE
);